# A minimal left prompt
format = '$directory$character'
# move the rest of the prompt to the right
right_format = """$all"""

add_newline = false

[character]
format = '[](cyan) '

[directory]
home_symbol = 'lutz'
style = 'blue'
truncation_length = 3
truncate_to_repo = true
read_only = ''
read_only_style = 'red'

[c]
format = '[ $version]($style) '
style = 'bold blue'

[container]
format = '[ $name]($style) '

[dart]
format = '[ $version]($style) '
style = 'bold blue'

[docker_context]
format = '[ $context]($style) '
style = 'bold blue'

[dotnet]
format = '[ $version]($style) '
style = 'bold blue'

[elixir]
format = '[ $version]($style) '
style = 'bold purple'

# TODO: Git related

[golang]
format = '[ $version]($style) '
style = 'bold cyan'

[java]
format = '[ $version]($style) '
style = 'bold red dimmed'

[kotlin]
format = '[ $version]($style) '
style = 'bold blue'

[lua]
format = '[ $version]($style) '
style = 'bold blue'

[nodejs]
format = '[ $version]($style) '
style = 'bold green'
detect_extensions = ['js', 'mjs', 'cjs']
detect_files = []
detect_folders = []

[python]
format = '[ $version]($style) '
style = 'bold yellow'
python_binary = 'python3'

[rust]
format = '[ $version]($style) '
style = 'bold red'

[swift]
format = '[ $version]($style) '
style = 'bold 202' # TODO: Change number color into text


[custom.typescript]
format = '[ $output]($style) '
style = 'bold blue'
detect_extensions = ['ts']
command = 'tsc --version | awk "{print $NF}"' # maps to $output - gets only the version number

[custom.react]
format = '[ $output]($style) '
style = 'bold blue'
detect_extensions = ['tsx', 'jsx']
command = 'npm view react version' # maps to $output


[aws]
format = '[󰸏($profile )(\($region\) )]($style)'
style = 'bold blue'
disabled = false

[azure]
format = '[ $subscription]($style) '
style = 'bold blue'
disabled = false

[gcloud]
format = '[󰅟 $account$project]($style) '
style = 'bold blue'
disabled = false

[kubernetes]
format = '[☸ $context( \($namespace\))]($style) '
style = 'bold cyan'
detect_files = ['k8s']
disabled = false



[package]
format = '[ $version]($style) '
style = 'bold 208' # TODO: Change number color into text
