#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# Polybar
$HOME/.config/polybar/bspwm.sh

# Keyboard Layout
setxkbmap -model abnt2 -layout br -variant abnt2

# Cursor style
xsetroot -cursor_name left_ptr

# Wallpaper
feh --bg-fill --randomize --no-fehbg ~/Media/wallpapers/

# Autostart
picom -f &
dunst &
