[module/audio]
    type = internal/pulseaudio
    sink = alsa_output.pci-0000_12_00.3.analog-stereo
    use-ui-max = true
    format-volume = <ramp-volume> <label-volume>
    label-muted = ""
    ramp-volume-0 = ""
    ramp-volume-1 = ""
    click-right = "pactl set-sink-volume @DEFAULT_SINK@ -1000"
    click-middle = "pavucontrol"
    interval = 5
    label-active-font = 1

[module/date]
    type = internal/date
    interval = 5
    date = %a, %b %d
    time = %k:%M
    label = %{T3}%date%%{T-}  %time%
    background = ${colors.background} 

[module/battery]
    type = internal/battery
    battery = BAT1
    adapter = ACAD
    full-at = 98
    format-charging = <ramp-capacity> <label-charging>
    format-discharging = <ramp-capacity> <label-discharging>
    format-full-prefix = " "
    format-full-prefix-foreground = ${colors.foreground}
    ramp-capacity-0 = 
    ramp-capacity-1 = 
    ramp-capacity-2 = 
    ramp-capacity-3 = 
    ramp-capacity-4 = 
    ramp-capacity-foreground = ${colors.foreground}

[module/powermenu]
    type = custom/menu
    expand-left = true
    format-spacing = 1
    label-open = ""
    label-close = ""
    label-separator = " "
    label-separator-foreground = ${colors.foreground}
    menu-0-0 = ""
    menu-0-0-exec = sudo reboot
    menu-0-1 = ""
    menu-0-1-exec = sudo poweroff

[module/term]
    type = custom/script
    exec = echo ""
    click-left = "alacritty"

[module/workspaces]
    type = internal/bspwm
    pin-workspaces = true
    inline-mode = false
    enable-click = true
    enable-scroll = false
    reverse-scroll = false
    fuzzy-match = true


    ws-icon-default = 

    ; Available tags:
    ;   <label-monitor>
    ;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
    ;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>

    format = <label-state>
    label-focused = ﱣ
    label-occupied = 
    label-urgent = 
    label-empty = 

    label-separator = "  "
    label-separator-padding = 0

[module/hostname]
    type = custom/script
    interval = 9999
    exec = echo $USER

[module/wallpaper]
    type = custom/script
    exec = echo ""
    click-left = feh --no-fehbg --bg-fill --randomize ~/Media/wallpapers/*

[module/print]
    type = custom/script
    exec = echo ""
    click-left = maim -s | xclip -selection clipboard -t image/png

[module/network]
    type = internal/network
    interface = wlp3s0
    interval = 1
    ping-interval = 3
    accumulate-stats = true
    unknown-as-up = true

    label-connected = "%{A1:networkmanager_dmenu &:}直%{A}"
    label-disconnected = %{A1:networkmanager_dmenu &:}睊%{A}"

[module/music]
    type = custom/script
    format-background = 
    exec = /home/lutz/.config/polybar/music.py -f '%{B#9f181818}%{A1:/home/lutz/.config/polybar/music.py previous:} 玲 %{A}%{A1:/home/lutz/.config/polybar/music.py play-pause:}{:t15:{title}:}{:title: - :}{:artist:t5:{artist}:}%{A}%{A1:/home/lutz/.config/polybar/music.py next:} 怜%{A} %{B-}'
    tail = true
